server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_game?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 226203
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        linger.ms: 10
        batch.size: 16384
        compression.type: gzip
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: armynb001@gmail.com
    password: phidang226
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: vod7dlQ9f9qr6tgzmxwCzoiMDC6bbNJ9qkTief1QfBZAHjFn/t0BR5UPF4qfjblI
  expiration: 86400000
  refresh-expiration: 604800000
logging:
  level:
    org.springframework: INFO
    com.web_game: DEBUG