server:
  port: 8085
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/web_game?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 226203
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.web_game.Inventory_Service.event,com.web_game.common.event
        spring.json.value.default.type: com.web_game.common.Event.InventoryEvent

logging:
  level:
    org.springframework: INFO
    com.web_game: DEBUG
gateway:
  url: localhost:8080